services:
  endpoints.token.create:
    class: ./../../api/endpoints/user-token/CreateUserToken
    arguments: ['@app.token.creator']

  endpoints.contacts.get:
    class: ./../../api/endpoints/contacts/GetContacts
    arguments: ['@app.contact.finder']
    
  endpoints.contacts.get-group-members:
    class: ./../../api/endpoints/contacts/GetGroupMembers
    arguments: ['@app.contact.finder']

  endpoints.messages.send:
    class: ./../../api/endpoints/messages/send
      
  endpoints.messages.ack:
    class: ./../../api/endpoints/messages/ack

  endpoints.health.checker:
    class: ./../../api/endpoints/health/checker

  endpoints.user-restriction.create:
    class: ./../../api/endpoints/user-restrictions/CreateUserRestriction
    arguments: ['@app.user-restriction.creator']

  endpoints.user-restriction.delete:
    class: ./../../api/endpoints/user-restrictions/delete
  