services:
  app.contact.finder:
    class: ./../../modules/contacts/application/ContactFinder
    arguments: ['@repository.contact', '@repository.user-restriction', '@shared.logger']

  app.token.creator:
    class: ./../../modules/user-tokens/application/TokenCreator
    arguments: ['@repository.user-token', '@shared.logger']

  app.user-restriction.creator:
    class: ./../../modules/user-restrictions/application/UserRestrictionCreator
    arguments: ['@repository.user-restriction', '@shared.logger']

  app.user-restriction.eliminator:
    class: ./../../modules/user-restrictions/application/UserRestrictionEliminator
    arguments: ['@repository.user-restriction', '@shared.logger']
    
  app.user-restriction.validator:
    class: ./../../modules/user-restrictions/application/UserRestrictionValidator
    arguments: ['@repository.user-restriction', '@shared.logger']

  app.message.messaging:
    factory:
      class: ./../../modules/messages/infrastructure/messaging/firebase/FirebaseMessaging
      method: 'connect'

  app.message.sender:
    class: ./../../modules/messages/application/MessageSender
    arguments: ['@app.message.messaging', '@repository.message', '@shared.logger']

  