services:
  modules.message.application.sender:
    class: ./../../modules/Message/application/firebase-message-sender

  modules.message.application.synchronizer:
    class: ./../../modules/Message/application/message-synchronizer

  controllers.messaging:
    class: ./../../services/_impl/firebase-messaging
    arguments: ['@modules.message.application.sender']

  controllers.synchronizer:
    class: ./../../services/_impl/synchronizer
    arguments: ['@modules.message.application.synchronizer']

  controllers.MessageSenderController:
    class: ./../../controllers/MessageSenderController
    
  controllers.MessageSynchronizerController:
    class: ./../../controllers/MessageSynchronizerController

  controllers.MessageACKController:
    class: ./../../controllers/MessageACKController

  controllers.TokenValidatorController:
    class: ./../../controllers/TokenValidatorController
  
  controllers.GetContactsController:
    class: ./../../controllers/GetContactsController