services:
  modules.message.application.synchronizer:
    class: ./../../modules/Message/application/message-synchronizer

  controllers.MessageSenderController:
    class: ./../../controllers/MessageSenderController
    
  controllers.MessageSynchronizerController:
    class: ./../../controllers/MessageSynchronizerController

  controllers.MessageACKController:
    class: ./../../controllers/MessageACKController

  controllers.TokenValidatorController:
    class: ./../../controllers/TokenValidatorController
  
  controllers.GetContactsController:
    class: ./../../controllers/GetContactsController
